package daemon

import (
	"context"
	"fmt"
	"log"
	"net"
	"os"
	"os/signal"
	"slices"
	"syscall"
	"time"

	emxv1 "github.com/ehsan200/em-xray/api/emxv1"
	"github.com/ehsan200/em-xray/core/xray"
	"github.com/ehsan200/em-xray/internal/paths"
	"google.golang.org/grpc"
)

// sigTerm is the signal used to ask a child (and the daemon) to stop gracefully.
var sigTerm = syscall.SIGTERM

// pickLoopbackPort returns a free loopback port starting at def and scanning
// upward, skipping any in avoid. This avoids a clash with another xray (e.g.
// the user's em-wall) already holding the default. Falls back to the default
// if the scan finds nothing free.
func pickLoopbackPort(logger *log.Logger, what string, def int, avoid ...int) int {
	for port := def; port < def+64; port++ {
		if slices.Contains(avoid, port) {
			continue
		}
		ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
		if err != nil {
			continue
		}
		ln.Close()
		if port != def {
			logger.Printf("%s port %d busy; using %d", what, def, port)
		}
		return port
	}
	return def
}

// Run is the daemon entrypoint (invoked by the detached `emx daemon run`). It
// binds the control socket, serves gRPC, supervises the xray child, and blocks
// until stopped by signal, context cancel, or the Shutdown RPC.
func Run(ctx context.Context) error {
	p := paths.Default()
	if err := p.EnsureDirs(); err != nil {
		return err
	}
	// TLS inbound certs are generated by `xray tls cert` (embedded binary).
	installTLSCertGen(p)
	if pid, ok := RunningPID(p); ok {
		return fmt.Errorf("daemon already running (pid %d)", pid)
	}
	// A daemon started by an older build lives in a different runtime dir and
	// would not be seen by the check above, yet it still owns the xray child.
	if dir, pid, ok := LegacyDaemon(p); ok {
		return fmt.Errorf("an emx daemon from a previous layout is running (pid %d, %s); stop it first so only one daemon owns %s", pid, dir, p.DB())
	}
	// Unix socket paths are capped by the kernel (sun_path: 104 on darwin,
	// 108 on linux). A real $XDG_RUNTIME_DIR (/run/user/<uid>) is short; guard
	// so an over-long override fails with a clear message, not bind EINVAL.
	if n := len(p.Socket()); n > 100 {
		return fmt.Errorf("socket path too long (%d bytes): set a shorter $XDG_RUNTIME_DIR: %s", n, p.Socket())
	}
	if err := writePID(p.PIDFile(), os.Getpid()); err != nil {
		return err
	}
	defer os.Remove(p.PIDFile())

	logger := log.New(os.Stderr, "", log.LstdFlags|log.Lmsgprefix)
	logger.SetPrefix("[emx] ")

	// Move xray's gRPC api port off a busy default (e.g. another xray already on
	// 11932) so config generation + every `xray api` call agree on a free port.
	xray.ApiPort = pickLoopbackPort(logger, "api", xray.DefaultApiPort)
	xray.MetricsPort = pickLoopbackPort(logger, "metrics", xray.DefaultMetricsPort, xray.ApiPort)

	// Fresh socket: a stale file from a crash would make Listen fail.
	_ = os.Remove(p.Socket())
	lis, err := net.Listen("unix", p.Socket())
	if err != nil {
		return fmt.Errorf("listen %s: %w", p.Socket(), err)
	}
	defer os.Remove(p.Socket())

	// No other daemon owns this box at this point (both checks above passed), so
	// any emx xray still running is an orphan from a killed daemon — it would
	// otherwise keep serving an old config on the same ports via SO_REUSEPORT.
	ReapStrayXray(p, logger)

	// An upgrade can move where the database is looked up; bring the previous
	// one forward so an existing configuration survives the change.
	if err := AdoptLegacyDB(p, logger); err != nil {
		return err
	}

	// Persistence + supervisor + subscription scheduler.
	store, err := xray.Open(p.DB())
	if err != nil {
		return fmt.Errorf("open db: %w", err)
	}
	defer store.Close()

	sup := NewSupervisor(store, p, logger)
	// A successful subscription refresh live-syncs the dialer pool — never a restart.
	fetcher := NewSubFetcher(store, logger, sup.SyncDialerMembers)

	// Bring xray up to match current state (starts the child if any entry is
	// routable). Node churn from the scheduler doesn't reconcile until masters
	// exist (P5/P6), so onChange is nil for now.
	if err := sup.Reconcile(); err != nil {
		logger.Printf("initial reconcile: %v", err)
	}
	fetcher.Start(ctx)

	// Sample xray per-tag byte counters into hourly buckets for the traffic view.
	NewTrafficSampler(store, sup, logger).Start(ctx)
	// A process can remain alive while its API/event loop is wedged. Probe it
	// independently of the crash watchdog and restart after repeated failures.
	sup.StartHealthMonitor(ctx)
	// Leave pool nodes that stay dead out of their pools (applied live).
	sup.StartNodeHealth(ctx)
	// Keep xray's logs from filling the disk (rolls past the configured cap).
	NewLogRotator(store, p, logger).Start(ctx)

	stop := make(chan struct{})
	srv := &Server{startTime: time.Now(), store: store, sup: sup, fetcher: fetcher, stop: stop}
	go updateChecker(ctx, srv, logger)

	gs := grpc.NewServer()
	emxv1.RegisterDaemonServer(gs, srv)
	go func() {
		if err := gs.Serve(lis); err != nil {
			logger.Printf("grpc serve ended: %v", err)
		}
	}()
	logger.Printf("daemon up (pid %d) on %s", os.Getpid(), p.Socket())

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	select {
	case <-ctx.Done():
		logger.Print("context cancelled — shutting down")
	case s := <-sig:
		logger.Printf("signal %s — shutting down", s)
	case <-stop:
		logger.Print("shutdown requested — shutting down")
	}

	sup.Stop()
	gs.GracefulStop()
	return nil
}
