// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: emx.proto

package emxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_emx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{0}
}

func (x *RenameRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type SetEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnabledRequest) Reset() {
	*x = SetEnabledRequest{}
	mi := &file_emx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledRequest) ProtoMessage() {}

func (x *SetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{1}
}

func (x *SetEnabledRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type WinnerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Master        string                 `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"` // winning member name ("" if none selected yet)
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`   // slotN-out-<key>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinnerInfo) Reset() {
	*x = WinnerInfo{}
	mi := &file_emx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnerInfo) ProtoMessage() {}

func (x *WinnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnerInfo.ProtoReflect.Descriptor instead.
func (*WinnerInfo) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{2}
}

func (x *WinnerInfo) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *WinnerInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WinnerInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type WinnersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winners       []*WinnerInfo          `protobuf:"bytes,1,rep,name=winners,proto3" json:"winners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinnersReply) Reset() {
	*x = WinnersReply{}
	mi := &file_emx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinnersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnersReply) ProtoMessage() {}

func (x *WinnersReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnersReply.ProtoReflect.Descriptor instead.
func (*WinnersReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{3}
}

func (x *WinnersReply) GetWinners() []*WinnerInfo {
	if x != nil {
		return x.Winners
	}
	return nil
}

type SubAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IntervalSec   int32                  `protobuf:"varint,4,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	NodeCap       int32                  `protobuf:"varint,5,opt,name=node_cap,json=nodeCap,proto3" json:"node_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAddRequest) Reset() {
	*x = SubAddRequest{}
	mi := &file_emx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAddRequest) ProtoMessage() {}

func (x *SubAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAddRequest.ProtoReflect.Descriptor instead.
func (*SubAddRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{4}
}

func (x *SubAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubAddRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubAddRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SubAddRequest) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *SubAddRequest) GetNodeCap() int32 {
	if x != nil {
		return x.NodeCap
	}
	return 0
}

type SubInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NodeCount     int32                  `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	ActiveCount   int32                  `protobuf:"varint,6,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Upload        int64                  `protobuf:"varint,8,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64                  `protobuf:"varint,9,opt,name=download,proto3" json:"download,omitempty"`
	Total         int64                  `protobuf:"varint,10,opt,name=total,proto3" json:"total,omitempty"`
	Expire        int64                  `protobuf:"varint,11,opt,name=expire,proto3" json:"expire,omitempty"`
	LastFetched   int64                  `protobuf:"varint,12,opt,name=last_fetched,json=lastFetched,proto3" json:"last_fetched,omitempty"` // unix seconds; 0 => never
	UserAgent     string                 `protobuf:"bytes,13,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IntervalSec   int32                  `protobuf:"varint,14,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	NodeCap       int32                  `protobuf:"varint,15,opt,name=node_cap,json=nodeCap,proto3" json:"node_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubInfo) Reset() {
	*x = SubInfo{}
	mi := &file_emx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubInfo) ProtoMessage() {}

func (x *SubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubInfo.ProtoReflect.Descriptor instead.
func (*SubInfo) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{5}
}

func (x *SubInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SubInfo) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *SubInfo) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *SubInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *SubInfo) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *SubInfo) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *SubInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubInfo) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *SubInfo) GetLastFetched() int64 {
	if x != nil {
		return x.LastFetched
	}
	return 0
}

func (x *SubInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SubInfo) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *SubInfo) GetNodeCap() int32 {
	if x != nil {
		return x.NodeCap
	}
	return 0
}

type SubReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           *SubInfo               `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubReply) Reset() {
	*x = SubReply{}
	mi := &file_emx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubReply) ProtoMessage() {}

func (x *SubReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubReply.ProtoReflect.Descriptor instead.
func (*SubReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{6}
}

func (x *SubReply) GetSub() *SubInfo {
	if x != nil {
		return x.Sub
	}
	return nil
}

type SubListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subs          []*SubInfo             `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubListReply) Reset() {
	*x = SubListReply{}
	mi := &file_emx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubListReply) ProtoMessage() {}

func (x *SubListReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubListReply.ProtoReflect.Descriptor instead.
func (*SubListReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{7}
}

func (x *SubListReply) GetSubs() []*SubInfo {
	if x != nil {
		return x.Subs
	}
	return nil
}

type SubRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefreshRequest) Reset() {
	*x = SubRefreshRequest{}
	mi := &file_emx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefreshRequest) ProtoMessage() {}

func (x *SubRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefreshRequest.ProtoReflect.Descriptor instead.
func (*SubRefreshRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{8}
}

func (x *SubRefreshRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubRefreshReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         int32                  `protobuf:"varint,1,opt,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefreshReply) Reset() {
	*x = SubRefreshReply{}
	mi := &file_emx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefreshReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefreshReply) ProtoMessage() {}

func (x *SubRefreshReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefreshReply.ProtoReflect.Descriptor instead.
func (*SubRefreshReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{9}
}

func (x *SubRefreshReply) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Disabled      bool                   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_emx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{10}
}

func (x *NodeInfo) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *NodeInfo) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *NodeInfo) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type SubNodesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubNodesReply) Reset() {
	*x = SubNodesReply{}
	mi := &file_emx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubNodesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubNodesReply) ProtoMessage() {}

func (x *SubNodesReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubNodesReply.ProtoReflect.Descriptor instead.
func (*SubNodesReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{11}
}

func (x *SubNodesReply) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SubNodeDisabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         uint32                 `protobuf:"varint,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Disabled      bool                   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubNodeDisabledRequest) Reset() {
	*x = SubNodeDisabledRequest{}
	mi := &file_emx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubNodeDisabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubNodeDisabledRequest) ProtoMessage() {}

func (x *SubNodeDisabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubNodeDisabledRequest.ProtoReflect.Descriptor instead.
func (*SubNodeDisabledRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{12}
}

func (x *SubNodeDisabledRequest) GetSubId() uint32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *SubNodeDisabledRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *SubNodeDisabledRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_emx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{13}
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_emx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{14}
}

func (x *IdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Duplicate an existing inbound/entry under a new name.
type DuplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"` // "" => "<source> copy"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuplicateRequest) Reset() {
	*x = DuplicateRequest{}
	mi := &file_emx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateRequest) ProtoMessage() {}

func (x *DuplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateRequest.ProtoReflect.Descriptor instead.
func (*DuplicateRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{15}
}

func (x *DuplicateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DuplicateRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// ConfigReply carries a config as pretty-printed JSON for editing.
type ConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigReply) Reset() {
	*x = ConfigReply{}
	mi := &file_emx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReply) ProtoMessage() {}

func (x *ConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReply.ProtoReflect.Descriptor instead.
func (*ConfigReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigReply) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// SetConfigRequest replaces a config from edited JSON.
type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_emx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{17}
}

func (x *SetConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetConfigRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_emx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{18}
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XrayVersion   string                 `protobuf:"bytes,2,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_emx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{19}
}

func (x *PingReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingReply) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_emx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{20}
}

type StatusReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonPid       int32                  `protobuf:"varint,1,opt,name=daemon_pid,json=daemonPid,proto3" json:"daemon_pid,omitempty"`
	UptimeSec       int64                  `protobuf:"varint,2,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	Xray            *XrayState             `protobuf:"bytes,3,opt,name=xray,proto3" json:"xray,omitempty"`
	LatestVersion   string                 `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`        // newest release tag the daemon has seen ("" = unknown)
	UpdateAvailable bool                   `protobuf:"varint,5,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"` // latest_version is newer than the running build
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_emx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{21}
}

func (x *StatusReply) GetDaemonPid() int32 {
	if x != nil {
		return x.DaemonPid
	}
	return 0
}

func (x *StatusReply) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

func (x *StatusReply) GetXray() *XrayState {
	if x != nil {
		return x.Xray
	}
	return nil
}

func (x *StatusReply) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *StatusReply) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

type XrayState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Restarts      int32                  `protobuf:"varint,3,opt,name=restarts,proto3" json:"restarts,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XrayState) Reset() {
	*x = XrayState{}
	mi := &file_emx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XrayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrayState) ProtoMessage() {}

func (x *XrayState) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrayState.ProtoReflect.Descriptor instead.
func (*XrayState) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{22}
}

func (x *XrayState) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *XrayState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *XrayState) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *XrayState) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_emx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{23}
}

type ShutdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReply) Reset() {
	*x = ShutdownReply{}
	mi := &file_emx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReply) ProtoMessage() {}

func (x *ShutdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReply.ProtoReflect.Descriptor instead.
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{24}
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Security      string                 `protobuf:"bytes,5,opt,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_emx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{25}
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Template) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Template) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

type TemplateListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateListReply) Reset() {
	*x = TemplateListReply{}
	mi := &file_emx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListReply) ProtoMessage() {}

func (x *TemplateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListReply.ProtoReflect.Descriptor instead.
func (*TemplateListReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{26}
}

func (x *TemplateListReply) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type EntryAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`                                     // share link to parse into an outbound (optional)
	OutboundJson  string                 `protobuf:"bytes,3,opt,name=outbound_json,json=outboundJson,proto3" json:"outbound_json,omitempty"` // raw outbound JSON (alternative to link)
	Dialer        string                 `protobuf:"bytes,4,opt,name=dialer,proto3" json:"dialer,omitempty"`                                 // non-empty => master
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryAddRequest) Reset() {
	*x = EntryAddRequest{}
	mi := &file_emx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryAddRequest) ProtoMessage() {}

func (x *EntryAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryAddRequest.ProtoReflect.Descriptor instead.
func (*EntryAddRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{27}
}

func (x *EntryAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntryAddRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *EntryAddRequest) GetOutboundJson() string {
	if x != nil {
		return x.OutboundJson
	}
	return ""
}

func (x *EntryAddRequest) GetDialer() string {
	if x != nil {
		return x.Dialer
	}
	return ""
}

func (x *EntryAddRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type EntryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsMaster      bool                   `protobuf:"varint,4,opt,name=is_master,json=isMaster,proto3" json:"is_master,omitempty"`
	Dialer        string                 `protobuf:"bytes,5,opt,name=dialer,proto3" json:"dialer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryInfo) Reset() {
	*x = EntryInfo{}
	mi := &file_emx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryInfo) ProtoMessage() {}

func (x *EntryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryInfo.ProtoReflect.Descriptor instead.
func (*EntryInfo) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{28}
}

func (x *EntryInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntryInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EntryInfo) GetIsMaster() bool {
	if x != nil {
		return x.IsMaster
	}
	return false
}

func (x *EntryInfo) GetDialer() string {
	if x != nil {
		return x.Dialer
	}
	return ""
}

type EntryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *EntryInfo             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryReply) Reset() {
	*x = EntryReply{}
	mi := &file_emx_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryReply) ProtoMessage() {}

func (x *EntryReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryReply.ProtoReflect.Descriptor instead.
func (*EntryReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{29}
}

func (x *EntryReply) GetEntry() *EntryInfo {
	if x != nil {
		return x.Entry
	}
	return nil
}

type EntryListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EntryInfo           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryListReply) Reset() {
	*x = EntryListReply{}
	mi := &file_emx_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryListReply) ProtoMessage() {}

func (x *EntryListReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryListReply.ProtoReflect.Descriptor instead.
func (*EntryListReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{30}
}

func (x *EntryListReply) GetEntries() []*EntryInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type InboundAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`                       // "" => default (vless-reality)
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                           // master:NAME | xray:NAME | direct
	PublicHost    string                 `protobuf:"bytes,4,opt,name=public_host,json=publicHost,proto3" json:"public_host,omitempty"` // address clients dial (for the share link)
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`                              // 0 => auto-assign
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundAddRequest) Reset() {
	*x = InboundAddRequest{}
	mi := &file_emx_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundAddRequest) ProtoMessage() {}

func (x *InboundAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundAddRequest.ProtoReflect.Descriptor instead.
func (*InboundAddRequest) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{31}
}

func (x *InboundAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundAddRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *InboundAddRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InboundAddRequest) GetPublicHost() string {
	if x != nil {
		return x.PublicHost
	}
	return ""
}

func (x *InboundAddRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type InboundInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Security      string                 `protobuf:"bytes,5,opt,name=security,proto3" json:"security,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Uuid          string                 `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PublicHost    string                 `protobuf:"bytes,9,opt,name=public_host,json=publicHost,proto3" json:"public_host,omitempty"`
	ShareLink     string                 `protobuf:"bytes,10,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundInfo) Reset() {
	*x = InboundInfo{}
	mi := &file_emx_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundInfo) ProtoMessage() {}

func (x *InboundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundInfo.ProtoReflect.Descriptor instead.
func (*InboundInfo) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{32}
}

func (x *InboundInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InboundInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InboundInfo) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *InboundInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InboundInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InboundInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *InboundInfo) GetPublicHost() string {
	if x != nil {
		return x.PublicHost
	}
	return ""
}

func (x *InboundInfo) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

type InboundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbound       *InboundInfo           `protobuf:"bytes,1,opt,name=inbound,proto3" json:"inbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundReply) Reset() {
	*x = InboundReply{}
	mi := &file_emx_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundReply) ProtoMessage() {}

func (x *InboundReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundReply.ProtoReflect.Descriptor instead.
func (*InboundReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{33}
}

func (x *InboundReply) GetInbound() *InboundInfo {
	if x != nil {
		return x.Inbound
	}
	return nil
}

type InboundListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbounds      []*InboundInfo         `protobuf:"bytes,1,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundListReply) Reset() {
	*x = InboundListReply{}
	mi := &file_emx_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundListReply) ProtoMessage() {}

func (x *InboundListReply) ProtoReflect() protoreflect.Message {
	mi := &file_emx_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundListReply.ProtoReflect.Descriptor instead.
func (*InboundListReply) Descriptor() ([]byte, []int) {
	return file_emx_proto_rawDescGZIP(), []int{34}
}

func (x *InboundListReply) GetInbounds() []*InboundInfo {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

var File_emx_proto protoreflect.FileDescriptor

const file_emx_proto_rawDesc = "" +
	"\n" +
	"\temx.proto\x12\x06emx.v1\":\n" +
	"\rRenameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"=\n" +
	"\x11SetEnabledRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"J\n" +
	"\n" +
	"WinnerInfo\x12\x16\n" +
	"\x06master\x18\x01 \x01(\tR\x06master\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"<\n" +
	"\fWinnersReply\x12,\n" +
	"\awinners\x18\x01 \x03(\v2\x12.emx.v1.WinnerInfoR\awinners\"\x92\x01\n" +
	"\rSubAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12!\n" +
	"\finterval_sec\x18\x04 \x01(\x05R\vintervalSec\x12\x19\n" +
	"\bnode_cap\x18\x05 \x01(\x05R\anodeCap\"\x9c\x03\n" +
	"\aSubInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"node_count\x18\x05 \x01(\x05R\tnodeCount\x12!\n" +
	"\factive_count\x18\x06 \x01(\x05R\vactiveCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12\x16\n" +
	"\x06upload\x18\b \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\t \x01(\x03R\bdownload\x12\x14\n" +
	"\x05total\x18\n" +
	" \x01(\x03R\x05total\x12\x16\n" +
	"\x06expire\x18\v \x01(\x03R\x06expire\x12!\n" +
	"\flast_fetched\x18\f \x01(\x03R\vlastFetched\x12\x1d\n" +
	"\n" +
	"user_agent\x18\r \x01(\tR\tuserAgent\x12!\n" +
	"\finterval_sec\x18\x0e \x01(\x05R\vintervalSec\x12\x19\n" +
	"\bnode_cap\x18\x0f \x01(\x05R\anodeCap\"-\n" +
	"\bSubReply\x12!\n" +
	"\x03sub\x18\x01 \x01(\v2\x0f.emx.v1.SubInfoR\x03sub\"3\n" +
	"\fSubListReply\x12#\n" +
	"\x04subs\x18\x01 \x03(\v2\x0f.emx.v1.SubInfoR\x04subs\"#\n" +
	"\x11SubRefreshRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"'\n" +
	"\x0fSubRefreshReply\x12\x14\n" +
	"\x05nodes\x18\x01 \x01(\x05R\x05nodes\"\x93\x01\n" +
	"\bNodeInfo\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\"7\n" +
	"\rSubNodesReply\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.emx.v1.NodeInfoR\x05nodes\"m\n" +
	"\x16SubNodeDisabledRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\rR\x05subId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"=\n" +
	"\x10DuplicateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"!\n" +
	"\vConfigReply\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"6\n" +
	"\x10SetConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"\r\n" +
	"\vPingRequest\"H\n" +
	"\tPingReply\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fxray_version\x18\x02 \x01(\tR\vxrayVersion\"\x0f\n" +
	"\rStatusRequest\"\xc4\x01\n" +
	"\vStatusReply\x12\x1d\n" +
	"\n" +
	"daemon_pid\x18\x01 \x01(\x05R\tdaemonPid\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x02 \x01(\x03R\tuptimeSec\x12%\n" +
	"\x04xray\x18\x03 \x01(\v2\x11.emx.v1.XrayStateR\x04xray\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12)\n" +
	"\x10update_available\x18\x05 \x01(\bR\x0fupdateAvailable\"r\n" +
	"\tXrayState\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1a\n" +
	"\brestarts\x18\x03 \x01(\x05R\brestarts\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"\x11\n" +
	"\x0fShutdownRequest\"\x0f\n" +
	"\rShutdownReply\"\x92\x01\n" +
	"\bTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x1a\n" +
	"\bsecurity\x18\x05 \x01(\tR\bsecurity\"C\n" +
	"\x11TemplateListReply\x12.\n" +
	"\ttemplates\x18\x01 \x03(\v2\x10.emx.v1.TemplateR\ttemplates\"\x90\x01\n" +
	"\x0fEntryAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12#\n" +
	"\routbound_json\x18\x03 \x01(\tR\foutboundJson\x12\x16\n" +
	"\x06dialer\x18\x04 \x01(\tR\x06dialer\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"~\n" +
	"\tEntryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1b\n" +
	"\tis_master\x18\x04 \x01(\bR\bisMaster\x12\x16\n" +
	"\x06dialer\x18\x05 \x01(\tR\x06dialer\"5\n" +
	"\n" +
	"EntryReply\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.emx.v1.EntryInfoR\x05entry\"=\n" +
	"\x0eEntryListReply\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.emx.v1.EntryInfoR\aentries\"\x90\x01\n" +
	"\x11InboundAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1f\n" +
	"\vpublic_host\x18\x04 \x01(\tR\n" +
	"publicHost\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"\x83\x02\n" +
	"\vInboundInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bsecurity\x18\x05 \x01(\tR\bsecurity\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\x12\n" +
	"\x04uuid\x18\b \x01(\tR\x04uuid\x12\x1f\n" +
	"\vpublic_host\x18\t \x01(\tR\n" +
	"publicHost\x12\x1d\n" +
	"\n" +
	"share_link\x18\n" +
	" \x01(\tR\tshareLink\"=\n" +
	"\fInboundReply\x12-\n" +
	"\ainbound\x18\x01 \x01(\v2\x13.emx.v1.InboundInfoR\ainbound\"C\n" +
	"\x10InboundListReply\x12/\n" +
	"\binbounds\x18\x01 \x03(\v2\x13.emx.v1.InboundInfoR\binbounds2\xcc\v\n" +
	"\x06Daemon\x12.\n" +
	"\x04Ping\x12\x13.emx.v1.PingRequest\x1a\x11.emx.v1.PingReply\x124\n" +
	"\x06Status\x12\x15.emx.v1.StatusRequest\x1a\x13.emx.v1.StatusReply\x12:\n" +
	"\bShutdown\x12\x17.emx.v1.ShutdownRequest\x1a\x15.emx.v1.ShutdownReply\x128\n" +
	"\fTemplateList\x12\r.emx.v1.Empty\x1a\x19.emx.v1.TemplateListReply\x127\n" +
	"\bEntryAdd\x12\x17.emx.v1.EntryAddRequest\x1a\x12.emx.v1.EntryReply\x122\n" +
	"\tEntryList\x12\r.emx.v1.Empty\x1a\x16.emx.v1.EntryListReply\x12/\n" +
	"\vEntryRemove\x12\x11.emx.v1.IdRequest\x1a\r.emx.v1.Empty\x123\n" +
	"\vEntryRename\x12\x15.emx.v1.RenameRequest\x1a\r.emx.v1.Empty\x12>\n" +
	"\x0eEntryDuplicate\x12\x18.emx.v1.DuplicateRequest\x1a\x12.emx.v1.EntryReply\x128\n" +
	"\x0eEntryGetConfig\x12\x11.emx.v1.IdRequest\x1a\x13.emx.v1.ConfigReply\x12>\n" +
	"\x0eEntrySetConfig\x12\x18.emx.v1.SetConfigRequest\x1a\x12.emx.v1.EntryReply\x12=\n" +
	"\n" +
	"InboundAdd\x12\x19.emx.v1.InboundAddRequest\x1a\x14.emx.v1.InboundReply\x126\n" +
	"\vInboundList\x12\r.emx.v1.Empty\x1a\x18.emx.v1.InboundListReply\x121\n" +
	"\rInboundRemove\x12\x11.emx.v1.IdRequest\x1a\r.emx.v1.Empty\x12B\n" +
	"\x10InboundDuplicate\x12\x18.emx.v1.DuplicateRequest\x1a\x14.emx.v1.InboundReply\x12:\n" +
	"\x10InboundGetConfig\x12\x11.emx.v1.IdRequest\x1a\x13.emx.v1.ConfigReply\x12B\n" +
	"\x10InboundSetConfig\x12\x18.emx.v1.SetConfigRequest\x1a\x14.emx.v1.InboundReply\x12.\n" +
	"\aWinners\x12\r.emx.v1.Empty\x1a\x14.emx.v1.WinnersReply\x121\n" +
	"\x06SubAdd\x12\x15.emx.v1.SubAddRequest\x1a\x10.emx.v1.SubReply\x12.\n" +
	"\aSubList\x12\r.emx.v1.Empty\x1a\x14.emx.v1.SubListReply\x12-\n" +
	"\tSubRemove\x12\x11.emx.v1.IdRequest\x1a\r.emx.v1.Empty\x129\n" +
	"\rSubSetEnabled\x12\x19.emx.v1.SetEnabledRequest\x1a\r.emx.v1.Empty\x12@\n" +
	"\n" +
	"SubRefresh\x12\x19.emx.v1.SubRefreshRequest\x1a\x17.emx.v1.SubRefreshReply\x124\n" +
	"\bSubNodes\x12\x11.emx.v1.IdRequest\x1a\x15.emx.v1.SubNodesReply\x12C\n" +
	"\x12SubSetNodeDisabled\x12\x1e.emx.v1.SubNodeDisabledRequest\x1a\r.emx.v1.Empty\x121\n" +
	"\tSubRename\x12\x15.emx.v1.RenameRequest\x1a\r.emx.v1.EmptyB-Z+github.com/ehsan200/em-xray/api/emxv1;emxv1b\x06proto3"

var (
	file_emx_proto_rawDescOnce sync.Once
	file_emx_proto_rawDescData []byte
)

func file_emx_proto_rawDescGZIP() []byte {
	file_emx_proto_rawDescOnce.Do(func() {
		file_emx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emx_proto_rawDesc), len(file_emx_proto_rawDesc)))
	})
	return file_emx_proto_rawDescData
}

var file_emx_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_emx_proto_goTypes = []any{
	(*RenameRequest)(nil),          // 0: emx.v1.RenameRequest
	(*SetEnabledRequest)(nil),      // 1: emx.v1.SetEnabledRequest
	(*WinnerInfo)(nil),             // 2: emx.v1.WinnerInfo
	(*WinnersReply)(nil),           // 3: emx.v1.WinnersReply
	(*SubAddRequest)(nil),          // 4: emx.v1.SubAddRequest
	(*SubInfo)(nil),                // 5: emx.v1.SubInfo
	(*SubReply)(nil),               // 6: emx.v1.SubReply
	(*SubListReply)(nil),           // 7: emx.v1.SubListReply
	(*SubRefreshRequest)(nil),      // 8: emx.v1.SubRefreshRequest
	(*SubRefreshReply)(nil),        // 9: emx.v1.SubRefreshReply
	(*NodeInfo)(nil),               // 10: emx.v1.NodeInfo
	(*SubNodesReply)(nil),          // 11: emx.v1.SubNodesReply
	(*SubNodeDisabledRequest)(nil), // 12: emx.v1.SubNodeDisabledRequest
	(*Empty)(nil),                  // 13: emx.v1.Empty
	(*IdRequest)(nil),              // 14: emx.v1.IdRequest
	(*DuplicateRequest)(nil),       // 15: emx.v1.DuplicateRequest
	(*ConfigReply)(nil),            // 16: emx.v1.ConfigReply
	(*SetConfigRequest)(nil),       // 17: emx.v1.SetConfigRequest
	(*PingRequest)(nil),            // 18: emx.v1.PingRequest
	(*PingReply)(nil),              // 19: emx.v1.PingReply
	(*StatusRequest)(nil),          // 20: emx.v1.StatusRequest
	(*StatusReply)(nil),            // 21: emx.v1.StatusReply
	(*XrayState)(nil),              // 22: emx.v1.XrayState
	(*ShutdownRequest)(nil),        // 23: emx.v1.ShutdownRequest
	(*ShutdownReply)(nil),          // 24: emx.v1.ShutdownReply
	(*Template)(nil),               // 25: emx.v1.Template
	(*TemplateListReply)(nil),      // 26: emx.v1.TemplateListReply
	(*EntryAddRequest)(nil),        // 27: emx.v1.EntryAddRequest
	(*EntryInfo)(nil),              // 28: emx.v1.EntryInfo
	(*EntryReply)(nil),             // 29: emx.v1.EntryReply
	(*EntryListReply)(nil),         // 30: emx.v1.EntryListReply
	(*InboundAddRequest)(nil),      // 31: emx.v1.InboundAddRequest
	(*InboundInfo)(nil),            // 32: emx.v1.InboundInfo
	(*InboundReply)(nil),           // 33: emx.v1.InboundReply
	(*InboundListReply)(nil),       // 34: emx.v1.InboundListReply
}
var file_emx_proto_depIdxs = []int32{
	2,  // 0: emx.v1.WinnersReply.winners:type_name -> emx.v1.WinnerInfo
	5,  // 1: emx.v1.SubReply.sub:type_name -> emx.v1.SubInfo
	5,  // 2: emx.v1.SubListReply.subs:type_name -> emx.v1.SubInfo
	10, // 3: emx.v1.SubNodesReply.nodes:type_name -> emx.v1.NodeInfo
	22, // 4: emx.v1.StatusReply.xray:type_name -> emx.v1.XrayState
	25, // 5: emx.v1.TemplateListReply.templates:type_name -> emx.v1.Template
	28, // 6: emx.v1.EntryReply.entry:type_name -> emx.v1.EntryInfo
	28, // 7: emx.v1.EntryListReply.entries:type_name -> emx.v1.EntryInfo
	32, // 8: emx.v1.InboundReply.inbound:type_name -> emx.v1.InboundInfo
	32, // 9: emx.v1.InboundListReply.inbounds:type_name -> emx.v1.InboundInfo
	18, // 10: emx.v1.Daemon.Ping:input_type -> emx.v1.PingRequest
	20, // 11: emx.v1.Daemon.Status:input_type -> emx.v1.StatusRequest
	23, // 12: emx.v1.Daemon.Shutdown:input_type -> emx.v1.ShutdownRequest
	13, // 13: emx.v1.Daemon.TemplateList:input_type -> emx.v1.Empty
	27, // 14: emx.v1.Daemon.EntryAdd:input_type -> emx.v1.EntryAddRequest
	13, // 15: emx.v1.Daemon.EntryList:input_type -> emx.v1.Empty
	14, // 16: emx.v1.Daemon.EntryRemove:input_type -> emx.v1.IdRequest
	0,  // 17: emx.v1.Daemon.EntryRename:input_type -> emx.v1.RenameRequest
	15, // 18: emx.v1.Daemon.EntryDuplicate:input_type -> emx.v1.DuplicateRequest
	14, // 19: emx.v1.Daemon.EntryGetConfig:input_type -> emx.v1.IdRequest
	17, // 20: emx.v1.Daemon.EntrySetConfig:input_type -> emx.v1.SetConfigRequest
	31, // 21: emx.v1.Daemon.InboundAdd:input_type -> emx.v1.InboundAddRequest
	13, // 22: emx.v1.Daemon.InboundList:input_type -> emx.v1.Empty
	14, // 23: emx.v1.Daemon.InboundRemove:input_type -> emx.v1.IdRequest
	15, // 24: emx.v1.Daemon.InboundDuplicate:input_type -> emx.v1.DuplicateRequest
	14, // 25: emx.v1.Daemon.InboundGetConfig:input_type -> emx.v1.IdRequest
	17, // 26: emx.v1.Daemon.InboundSetConfig:input_type -> emx.v1.SetConfigRequest
	13, // 27: emx.v1.Daemon.Winners:input_type -> emx.v1.Empty
	4,  // 28: emx.v1.Daemon.SubAdd:input_type -> emx.v1.SubAddRequest
	13, // 29: emx.v1.Daemon.SubList:input_type -> emx.v1.Empty
	14, // 30: emx.v1.Daemon.SubRemove:input_type -> emx.v1.IdRequest
	1,  // 31: emx.v1.Daemon.SubSetEnabled:input_type -> emx.v1.SetEnabledRequest
	8,  // 32: emx.v1.Daemon.SubRefresh:input_type -> emx.v1.SubRefreshRequest
	14, // 33: emx.v1.Daemon.SubNodes:input_type -> emx.v1.IdRequest
	12, // 34: emx.v1.Daemon.SubSetNodeDisabled:input_type -> emx.v1.SubNodeDisabledRequest
	0,  // 35: emx.v1.Daemon.SubRename:input_type -> emx.v1.RenameRequest
	19, // 36: emx.v1.Daemon.Ping:output_type -> emx.v1.PingReply
	21, // 37: emx.v1.Daemon.Status:output_type -> emx.v1.StatusReply
	24, // 38: emx.v1.Daemon.Shutdown:output_type -> emx.v1.ShutdownReply
	26, // 39: emx.v1.Daemon.TemplateList:output_type -> emx.v1.TemplateListReply
	29, // 40: emx.v1.Daemon.EntryAdd:output_type -> emx.v1.EntryReply
	30, // 41: emx.v1.Daemon.EntryList:output_type -> emx.v1.EntryListReply
	13, // 42: emx.v1.Daemon.EntryRemove:output_type -> emx.v1.Empty
	13, // 43: emx.v1.Daemon.EntryRename:output_type -> emx.v1.Empty
	29, // 44: emx.v1.Daemon.EntryDuplicate:output_type -> emx.v1.EntryReply
	16, // 45: emx.v1.Daemon.EntryGetConfig:output_type -> emx.v1.ConfigReply
	29, // 46: emx.v1.Daemon.EntrySetConfig:output_type -> emx.v1.EntryReply
	33, // 47: emx.v1.Daemon.InboundAdd:output_type -> emx.v1.InboundReply
	34, // 48: emx.v1.Daemon.InboundList:output_type -> emx.v1.InboundListReply
	13, // 49: emx.v1.Daemon.InboundRemove:output_type -> emx.v1.Empty
	33, // 50: emx.v1.Daemon.InboundDuplicate:output_type -> emx.v1.InboundReply
	16, // 51: emx.v1.Daemon.InboundGetConfig:output_type -> emx.v1.ConfigReply
	33, // 52: emx.v1.Daemon.InboundSetConfig:output_type -> emx.v1.InboundReply
	3,  // 53: emx.v1.Daemon.Winners:output_type -> emx.v1.WinnersReply
	6,  // 54: emx.v1.Daemon.SubAdd:output_type -> emx.v1.SubReply
	7,  // 55: emx.v1.Daemon.SubList:output_type -> emx.v1.SubListReply
	13, // 56: emx.v1.Daemon.SubRemove:output_type -> emx.v1.Empty
	13, // 57: emx.v1.Daemon.SubSetEnabled:output_type -> emx.v1.Empty
	9,  // 58: emx.v1.Daemon.SubRefresh:output_type -> emx.v1.SubRefreshReply
	11, // 59: emx.v1.Daemon.SubNodes:output_type -> emx.v1.SubNodesReply
	13, // 60: emx.v1.Daemon.SubSetNodeDisabled:output_type -> emx.v1.Empty
	13, // 61: emx.v1.Daemon.SubRename:output_type -> emx.v1.Empty
	36, // [36:62] is the sub-list for method output_type
	10, // [10:36] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_emx_proto_init() }
func file_emx_proto_init() {
	if File_emx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emx_proto_rawDesc), len(file_emx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emx_proto_goTypes,
		DependencyIndexes: file_emx_proto_depIdxs,
		MessageInfos:      file_emx_proto_msgTypes,
	}.Build()
	File_emx_proto = out.File
	file_emx_proto_goTypes = nil
	file_emx_proto_depIdxs = nil
}
