// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: emx.proto

package emxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daemon_Ping_FullMethodName                  = "/emx.v1.Daemon/Ping"
	Daemon_Status_FullMethodName                = "/emx.v1.Daemon/Status"
	Daemon_Shutdown_FullMethodName              = "/emx.v1.Daemon/Shutdown"
	Daemon_XrayRestart_FullMethodName           = "/emx.v1.Daemon/XrayRestart"
	Daemon_Test_FullMethodName                  = "/emx.v1.Daemon/Test"
	Daemon_XrayConfig_FullMethodName            = "/emx.v1.Daemon/XrayConfig"
	Daemon_LogLevel_FullMethodName              = "/emx.v1.Daemon/LogLevel"
	Daemon_LogCap_FullMethodName                = "/emx.v1.Daemon/LogCap"
	Daemon_ProbeInterval_FullMethodName         = "/emx.v1.Daemon/ProbeInterval"
	Daemon_TemplateList_FullMethodName          = "/emx.v1.Daemon/TemplateList"
	Daemon_EntryAdd_FullMethodName              = "/emx.v1.Daemon/EntryAdd"
	Daemon_EntryList_FullMethodName             = "/emx.v1.Daemon/EntryList"
	Daemon_EntryRemove_FullMethodName           = "/emx.v1.Daemon/EntryRemove"
	Daemon_EntryRename_FullMethodName           = "/emx.v1.Daemon/EntryRename"
	Daemon_EntryDuplicate_FullMethodName        = "/emx.v1.Daemon/EntryDuplicate"
	Daemon_EntryGetConfig_FullMethodName        = "/emx.v1.Daemon/EntryGetConfig"
	Daemon_EntrySetConfig_FullMethodName        = "/emx.v1.Daemon/EntrySetConfig"
	Daemon_EntrySetMux_FullMethodName           = "/emx.v1.Daemon/EntrySetMux"
	Daemon_InboundAdd_FullMethodName            = "/emx.v1.Daemon/InboundAdd"
	Daemon_InboundList_FullMethodName           = "/emx.v1.Daemon/InboundList"
	Daemon_InboundRemove_FullMethodName         = "/emx.v1.Daemon/InboundRemove"
	Daemon_InboundDuplicate_FullMethodName      = "/emx.v1.Daemon/InboundDuplicate"
	Daemon_InboundGetConfig_FullMethodName      = "/emx.v1.Daemon/InboundGetConfig"
	Daemon_InboundSetConfig_FullMethodName      = "/emx.v1.Daemon/InboundSetConfig"
	Daemon_InboundUserAdd_FullMethodName        = "/emx.v1.Daemon/InboundUserAdd"
	Daemon_InboundUserList_FullMethodName       = "/emx.v1.Daemon/InboundUserList"
	Daemon_InboundUserRemove_FullMethodName     = "/emx.v1.Daemon/InboundUserRemove"
	Daemon_InboundUserSetEnabled_FullMethodName = "/emx.v1.Daemon/InboundUserSetEnabled"
	Daemon_Winners_FullMethodName               = "/emx.v1.Daemon/Winners"
	Daemon_Traffic_FullMethodName               = "/emx.v1.Daemon/Traffic"
	Daemon_TrafficLive_FullMethodName           = "/emx.v1.Daemon/TrafficLive"
	Daemon_TrafficRetention_FullMethodName      = "/emx.v1.Daemon/TrafficRetention"
	Daemon_ExportConfig_FullMethodName          = "/emx.v1.Daemon/ExportConfig"
	Daemon_ImportConfig_FullMethodName          = "/emx.v1.Daemon/ImportConfig"
	Daemon_SubAdd_FullMethodName                = "/emx.v1.Daemon/SubAdd"
	Daemon_SubList_FullMethodName               = "/emx.v1.Daemon/SubList"
	Daemon_SubRemove_FullMethodName             = "/emx.v1.Daemon/SubRemove"
	Daemon_SubSetEnabled_FullMethodName         = "/emx.v1.Daemon/SubSetEnabled"
	Daemon_SubRefresh_FullMethodName            = "/emx.v1.Daemon/SubRefresh"
	Daemon_SubNodes_FullMethodName              = "/emx.v1.Daemon/SubNodes"
	Daemon_SubSetNodeDisabled_FullMethodName    = "/emx.v1.Daemon/SubSetNodeDisabled"
	Daemon_SubRename_FullMethodName             = "/emx.v1.Daemon/SubRename"
	Daemon_SubSetOptions_FullMethodName         = "/emx.v1.Daemon/SubSetOptions"
)

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Daemon is the control surface the CLI/TUI drives over the unix socket.
type DaemonClient interface {
	// Lifecycle / health.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	// Diagnostics / settings.
	XrayRestart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*XrayRestartReply, error)
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
	XrayConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigReply, error)
	LogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelReply, error)
	LogCap(ctx context.Context, in *LogCapRequest, opts ...grpc.CallOption) (*LogCapReply, error)
	ProbeInterval(ctx context.Context, in *ProbeIntervalRequest, opts ...grpc.CallOption) (*ProbeIntervalReply, error)
	// Templates.
	TemplateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateListReply, error)
	// Entries (outbounds; a non-empty dialer makes one a master).
	EntryAdd(ctx context.Context, in *EntryAddRequest, opts ...grpc.CallOption) (*EntryReply, error)
	EntryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntryListReply, error)
	EntryRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	EntryRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error)
	EntryDuplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*EntryReply, error)
	EntryGetConfig(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ConfigReply, error)
	EntrySetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*EntryReply, error)
	EntrySetMux(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*EntryReply, error)
	// Inbounds (server listeners routed to a target).
	InboundAdd(ctx context.Context, in *InboundAddRequest, opts ...grpc.CallOption) (*InboundReply, error)
	InboundList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InboundListReply, error)
	InboundRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	InboundDuplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*InboundReply, error)
	InboundGetConfig(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ConfigReply, error)
	InboundSetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*InboundReply, error)
	// Multi-user: extra clients on an inbound with per-user traffic + byte caps.
	InboundUserAdd(ctx context.Context, in *InboundUserAddRequest, opts ...grpc.CallOption) (*InboundUserReply, error)
	InboundUserList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*InboundUserListReply, error)
	InboundUserRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	InboundUserSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error)
	// Winner: the current fastest (balancer-selected) node per master.
	Winners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WinnersReply, error)
	// Traffic: per-inbound/outbound byte totals + hourly buckets for charts.
	Traffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficReply, error)
	// TrafficLive: current cumulative counters, for a client-computed live rate.
	TrafficLive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrafficLiveReply, error)
	// TrafficRetention: read/set how many days of hourly buckets are kept.
	TrafficRetention(ctx context.Context, in *TrafficRetentionRequest, opts ...grpc.CallOption) (*TrafficRetentionReply, error)
	// Backup / restore the full config (inbounds + entries + subscriptions).
	ExportConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigReply, error)
	ImportConfig(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportReply, error)
	// Subscriptions (node pools consumed by masters via xraysub:NAME).
	SubAdd(ctx context.Context, in *SubAddRequest, opts ...grpc.CallOption) (*SubReply, error)
	SubList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubListReply, error)
	SubRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	SubSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error)
	SubRefresh(ctx context.Context, in *SubRefreshRequest, opts ...grpc.CallOption) (*SubRefreshReply, error)
	SubNodes(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SubNodesReply, error)
	SubSetNodeDisabled(ctx context.Context, in *SubNodeDisabledRequest, opts ...grpc.CallOption) (*Empty, error)
	SubRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error)
	SubSetOptions(ctx context.Context, in *SubOptionsRequest, opts ...grpc.CallOption) (*SubReply, error)
}

type daemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonClient(cc grpc.ClientConnInterface) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, Daemon_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, Daemon_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, Daemon_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) XrayRestart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*XrayRestartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XrayRestartReply)
	err := c.cc.Invoke(ctx, Daemon_XrayRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestReply)
	err := c.cc.Invoke(ctx, Daemon_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) XrayConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, Daemon_XrayConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) LogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelReply)
	err := c.cc.Invoke(ctx, Daemon_LogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) LogCap(ctx context.Context, in *LogCapRequest, opts ...grpc.CallOption) (*LogCapReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogCapReply)
	err := c.cc.Invoke(ctx, Daemon_LogCap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ProbeInterval(ctx context.Context, in *ProbeIntervalRequest, opts ...grpc.CallOption) (*ProbeIntervalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeIntervalReply)
	err := c.cc.Invoke(ctx, Daemon_ProbeInterval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) TemplateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateListReply)
	err := c.cc.Invoke(ctx, Daemon_TemplateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryAdd(ctx context.Context, in *EntryAddRequest, opts ...grpc.CallOption) (*EntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryReply)
	err := c.cc.Invoke(ctx, Daemon_EntryAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntryListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryListReply)
	err := c.cc.Invoke(ctx, Daemon_EntryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_EntryRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_EntryRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryDuplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*EntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryReply)
	err := c.cc.Invoke(ctx, Daemon_EntryDuplicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryGetConfig(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, Daemon_EntryGetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntrySetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*EntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryReply)
	err := c.cc.Invoke(ctx, Daemon_EntrySetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntrySetMux(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*EntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryReply)
	err := c.cc.Invoke(ctx, Daemon_EntrySetMux_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundAdd(ctx context.Context, in *InboundAddRequest, opts ...grpc.CallOption) (*InboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundReply)
	err := c.cc.Invoke(ctx, Daemon_InboundAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InboundListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundListReply)
	err := c.cc.Invoke(ctx, Daemon_InboundList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_InboundRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundDuplicate(ctx context.Context, in *DuplicateRequest, opts ...grpc.CallOption) (*InboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundReply)
	err := c.cc.Invoke(ctx, Daemon_InboundDuplicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundGetConfig(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, Daemon_InboundGetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundSetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*InboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundReply)
	err := c.cc.Invoke(ctx, Daemon_InboundSetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundUserAdd(ctx context.Context, in *InboundUserAddRequest, opts ...grpc.CallOption) (*InboundUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundUserReply)
	err := c.cc.Invoke(ctx, Daemon_InboundUserAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundUserList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*InboundUserListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundUserListReply)
	err := c.cc.Invoke(ctx, Daemon_InboundUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundUserRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_InboundUserRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundUserSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_InboundUserSetEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Winners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WinnersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WinnersReply)
	err := c.cc.Invoke(ctx, Daemon_Winners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Traffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficReply)
	err := c.cc.Invoke(ctx, Daemon_Traffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) TrafficLive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrafficLiveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficLiveReply)
	err := c.cc.Invoke(ctx, Daemon_TrafficLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) TrafficRetention(ctx context.Context, in *TrafficRetentionRequest, opts ...grpc.CallOption) (*TrafficRetentionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficRetentionReply)
	err := c.cc.Invoke(ctx, Daemon_TrafficRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ExportConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, Daemon_ExportConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ImportConfig(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportReply)
	err := c.cc.Invoke(ctx, Daemon_ImportConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubAdd(ctx context.Context, in *SubAddRequest, opts ...grpc.CallOption) (*SubReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubReply)
	err := c.cc.Invoke(ctx, Daemon_SubAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubListReply)
	err := c.cc.Invoke(ctx, Daemon_SubList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubSetEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRefresh(ctx context.Context, in *SubRefreshRequest, opts ...grpc.CallOption) (*SubRefreshReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubRefreshReply)
	err := c.cc.Invoke(ctx, Daemon_SubRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubNodes(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SubNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubNodesReply)
	err := c.cc.Invoke(ctx, Daemon_SubNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubSetNodeDisabled(ctx context.Context, in *SubNodeDisabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubSetNodeDisabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubSetOptions(ctx context.Context, in *SubOptionsRequest, opts ...grpc.CallOption) (*SubReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubReply)
	err := c.cc.Invoke(ctx, Daemon_SubSetOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
// All implementations must embed UnimplementedDaemonServer
// for forward compatibility.
//
// Daemon is the control surface the CLI/TUI drives over the unix socket.
type DaemonServer interface {
	// Lifecycle / health.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	// Diagnostics / settings.
	XrayRestart(context.Context, *Empty) (*XrayRestartReply, error)
	Test(context.Context, *TestRequest) (*TestReply, error)
	XrayConfig(context.Context, *Empty) (*ConfigReply, error)
	LogLevel(context.Context, *LogLevelRequest) (*LogLevelReply, error)
	LogCap(context.Context, *LogCapRequest) (*LogCapReply, error)
	ProbeInterval(context.Context, *ProbeIntervalRequest) (*ProbeIntervalReply, error)
	// Templates.
	TemplateList(context.Context, *Empty) (*TemplateListReply, error)
	// Entries (outbounds; a non-empty dialer makes one a master).
	EntryAdd(context.Context, *EntryAddRequest) (*EntryReply, error)
	EntryList(context.Context, *Empty) (*EntryListReply, error)
	EntryRemove(context.Context, *IdRequest) (*Empty, error)
	EntryRename(context.Context, *RenameRequest) (*Empty, error)
	EntryDuplicate(context.Context, *DuplicateRequest) (*EntryReply, error)
	EntryGetConfig(context.Context, *IdRequest) (*ConfigReply, error)
	EntrySetConfig(context.Context, *SetConfigRequest) (*EntryReply, error)
	EntrySetMux(context.Context, *SetEnabledRequest) (*EntryReply, error)
	// Inbounds (server listeners routed to a target).
	InboundAdd(context.Context, *InboundAddRequest) (*InboundReply, error)
	InboundList(context.Context, *Empty) (*InboundListReply, error)
	InboundRemove(context.Context, *IdRequest) (*Empty, error)
	InboundDuplicate(context.Context, *DuplicateRequest) (*InboundReply, error)
	InboundGetConfig(context.Context, *IdRequest) (*ConfigReply, error)
	InboundSetConfig(context.Context, *SetConfigRequest) (*InboundReply, error)
	// Multi-user: extra clients on an inbound with per-user traffic + byte caps.
	InboundUserAdd(context.Context, *InboundUserAddRequest) (*InboundUserReply, error)
	InboundUserList(context.Context, *IdRequest) (*InboundUserListReply, error)
	InboundUserRemove(context.Context, *IdRequest) (*Empty, error)
	InboundUserSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error)
	// Winner: the current fastest (balancer-selected) node per master.
	Winners(context.Context, *Empty) (*WinnersReply, error)
	// Traffic: per-inbound/outbound byte totals + hourly buckets for charts.
	Traffic(context.Context, *TrafficRequest) (*TrafficReply, error)
	// TrafficLive: current cumulative counters, for a client-computed live rate.
	TrafficLive(context.Context, *Empty) (*TrafficLiveReply, error)
	// TrafficRetention: read/set how many days of hourly buckets are kept.
	TrafficRetention(context.Context, *TrafficRetentionRequest) (*TrafficRetentionReply, error)
	// Backup / restore the full config (inbounds + entries + subscriptions).
	ExportConfig(context.Context, *Empty) (*ConfigReply, error)
	ImportConfig(context.Context, *ImportRequest) (*ImportReply, error)
	// Subscriptions (node pools consumed by masters via xraysub:NAME).
	SubAdd(context.Context, *SubAddRequest) (*SubReply, error)
	SubList(context.Context, *Empty) (*SubListReply, error)
	SubRemove(context.Context, *IdRequest) (*Empty, error)
	SubSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error)
	SubRefresh(context.Context, *SubRefreshRequest) (*SubRefreshReply, error)
	SubNodes(context.Context, *IdRequest) (*SubNodesReply, error)
	SubSetNodeDisabled(context.Context, *SubNodeDisabledRequest) (*Empty, error)
	SubRename(context.Context, *RenameRequest) (*Empty, error)
	SubSetOptions(context.Context, *SubOptionsRequest) (*SubReply, error)
	mustEmbedUnimplementedDaemonServer()
}

// UnimplementedDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServer struct{}

func (UnimplementedDaemonServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServer) Status(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDaemonServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServer) XrayRestart(context.Context, *Empty) (*XrayRestartReply, error) {
	return nil, status.Error(codes.Unimplemented, "method XrayRestart not implemented")
}
func (UnimplementedDaemonServer) Test(context.Context, *TestRequest) (*TestReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedDaemonServer) XrayConfig(context.Context, *Empty) (*ConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method XrayConfig not implemented")
}
func (UnimplementedDaemonServer) LogLevel(context.Context, *LogLevelRequest) (*LogLevelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LogLevel not implemented")
}
func (UnimplementedDaemonServer) LogCap(context.Context, *LogCapRequest) (*LogCapReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LogCap not implemented")
}
func (UnimplementedDaemonServer) ProbeInterval(context.Context, *ProbeIntervalRequest) (*ProbeIntervalReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeInterval not implemented")
}
func (UnimplementedDaemonServer) TemplateList(context.Context, *Empty) (*TemplateListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TemplateList not implemented")
}
func (UnimplementedDaemonServer) EntryAdd(context.Context, *EntryAddRequest) (*EntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryAdd not implemented")
}
func (UnimplementedDaemonServer) EntryList(context.Context, *Empty) (*EntryListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryList not implemented")
}
func (UnimplementedDaemonServer) EntryRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryRemove not implemented")
}
func (UnimplementedDaemonServer) EntryRename(context.Context, *RenameRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryRename not implemented")
}
func (UnimplementedDaemonServer) EntryDuplicate(context.Context, *DuplicateRequest) (*EntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryDuplicate not implemented")
}
func (UnimplementedDaemonServer) EntryGetConfig(context.Context, *IdRequest) (*ConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntryGetConfig not implemented")
}
func (UnimplementedDaemonServer) EntrySetConfig(context.Context, *SetConfigRequest) (*EntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntrySetConfig not implemented")
}
func (UnimplementedDaemonServer) EntrySetMux(context.Context, *SetEnabledRequest) (*EntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EntrySetMux not implemented")
}
func (UnimplementedDaemonServer) InboundAdd(context.Context, *InboundAddRequest) (*InboundReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundAdd not implemented")
}
func (UnimplementedDaemonServer) InboundList(context.Context, *Empty) (*InboundListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundList not implemented")
}
func (UnimplementedDaemonServer) InboundRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundRemove not implemented")
}
func (UnimplementedDaemonServer) InboundDuplicate(context.Context, *DuplicateRequest) (*InboundReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundDuplicate not implemented")
}
func (UnimplementedDaemonServer) InboundGetConfig(context.Context, *IdRequest) (*ConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundGetConfig not implemented")
}
func (UnimplementedDaemonServer) InboundSetConfig(context.Context, *SetConfigRequest) (*InboundReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundSetConfig not implemented")
}
func (UnimplementedDaemonServer) InboundUserAdd(context.Context, *InboundUserAddRequest) (*InboundUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundUserAdd not implemented")
}
func (UnimplementedDaemonServer) InboundUserList(context.Context, *IdRequest) (*InboundUserListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundUserList not implemented")
}
func (UnimplementedDaemonServer) InboundUserRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundUserRemove not implemented")
}
func (UnimplementedDaemonServer) InboundUserSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InboundUserSetEnabled not implemented")
}
func (UnimplementedDaemonServer) Winners(context.Context, *Empty) (*WinnersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Winners not implemented")
}
func (UnimplementedDaemonServer) Traffic(context.Context, *TrafficRequest) (*TrafficReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Traffic not implemented")
}
func (UnimplementedDaemonServer) TrafficLive(context.Context, *Empty) (*TrafficLiveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TrafficLive not implemented")
}
func (UnimplementedDaemonServer) TrafficRetention(context.Context, *TrafficRetentionRequest) (*TrafficRetentionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TrafficRetention not implemented")
}
func (UnimplementedDaemonServer) ExportConfig(context.Context, *Empty) (*ConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportConfig not implemented")
}
func (UnimplementedDaemonServer) ImportConfig(context.Context, *ImportRequest) (*ImportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportConfig not implemented")
}
func (UnimplementedDaemonServer) SubAdd(context.Context, *SubAddRequest) (*SubReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubAdd not implemented")
}
func (UnimplementedDaemonServer) SubList(context.Context, *Empty) (*SubListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubList not implemented")
}
func (UnimplementedDaemonServer) SubRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubRemove not implemented")
}
func (UnimplementedDaemonServer) SubSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubSetEnabled not implemented")
}
func (UnimplementedDaemonServer) SubRefresh(context.Context, *SubRefreshRequest) (*SubRefreshReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubRefresh not implemented")
}
func (UnimplementedDaemonServer) SubNodes(context.Context, *IdRequest) (*SubNodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubNodes not implemented")
}
func (UnimplementedDaemonServer) SubSetNodeDisabled(context.Context, *SubNodeDisabledRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubSetNodeDisabled not implemented")
}
func (UnimplementedDaemonServer) SubRename(context.Context, *RenameRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubRename not implemented")
}
func (UnimplementedDaemonServer) SubSetOptions(context.Context, *SubOptionsRequest) (*SubReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubSetOptions not implemented")
}
func (UnimplementedDaemonServer) mustEmbedUnimplementedDaemonServer() {}
func (UnimplementedDaemonServer) testEmbeddedByValue()                {}

// UnsafeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServer will
// result in compilation errors.
type UnsafeDaemonServer interface {
	mustEmbedUnimplementedDaemonServer()
}

func RegisterDaemonServer(s grpc.ServiceRegistrar, srv DaemonServer) {
	// If the following call panics, it indicates UnimplementedDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daemon_ServiceDesc, srv)
}

func _Daemon_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_XrayRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).XrayRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_XrayRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).XrayRestart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_XrayConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).XrayConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_XrayConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).XrayConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_LogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).LogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_LogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).LogLevel(ctx, req.(*LogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_LogCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).LogCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_LogCap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).LogCap(ctx, req.(*LogCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ProbeInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeIntervalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ProbeInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ProbeInterval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ProbeInterval(ctx, req.(*ProbeIntervalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_TemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).TemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_TemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).TemplateList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryAdd(ctx, req.(*EntryAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryDuplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryDuplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryDuplicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryDuplicate(ctx, req.(*DuplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryGetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryGetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryGetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryGetConfig(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntrySetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntrySetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntrySetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntrySetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntrySetMux_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntrySetMux(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntrySetMux_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntrySetMux(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundAdd(ctx, req.(*InboundAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundDuplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundDuplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundDuplicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundDuplicate(ctx, req.(*DuplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundGetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundGetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundGetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundGetConfig(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundSetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundSetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundSetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundSetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundUserAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundUserAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundUserAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundUserAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundUserAdd(ctx, req.(*InboundUserAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundUserList(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundUserRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundUserRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundUserRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundUserRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundUserSetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundUserSetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundUserSetEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundUserSetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Winners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Winners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Winners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Winners(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Traffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Traffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Traffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Traffic(ctx, req.(*TrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_TrafficLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).TrafficLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_TrafficLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).TrafficLive(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_TrafficRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).TrafficRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_TrafficRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).TrafficRetention(ctx, req.(*TrafficRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ExportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ExportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ExportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ExportConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ImportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ImportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ImportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ImportConfig(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubAdd(ctx, req.(*SubAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubSetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubSetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubSetEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubSetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRefresh(ctx, req.(*SubRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubNodes(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubSetNodeDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNodeDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubSetNodeDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubSetNodeDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubSetNodeDisabled(ctx, req.(*SubNodeDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubSetOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubSetOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubSetOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubSetOptions(ctx, req.(*SubOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Daemon_ServiceDesc is the grpc.ServiceDesc for Daemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emx.v1.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Daemon_Ping_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Daemon_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Daemon_Shutdown_Handler,
		},
		{
			MethodName: "XrayRestart",
			Handler:    _Daemon_XrayRestart_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Daemon_Test_Handler,
		},
		{
			MethodName: "XrayConfig",
			Handler:    _Daemon_XrayConfig_Handler,
		},
		{
			MethodName: "LogLevel",
			Handler:    _Daemon_LogLevel_Handler,
		},
		{
			MethodName: "LogCap",
			Handler:    _Daemon_LogCap_Handler,
		},
		{
			MethodName: "ProbeInterval",
			Handler:    _Daemon_ProbeInterval_Handler,
		},
		{
			MethodName: "TemplateList",
			Handler:    _Daemon_TemplateList_Handler,
		},
		{
			MethodName: "EntryAdd",
			Handler:    _Daemon_EntryAdd_Handler,
		},
		{
			MethodName: "EntryList",
			Handler:    _Daemon_EntryList_Handler,
		},
		{
			MethodName: "EntryRemove",
			Handler:    _Daemon_EntryRemove_Handler,
		},
		{
			MethodName: "EntryRename",
			Handler:    _Daemon_EntryRename_Handler,
		},
		{
			MethodName: "EntryDuplicate",
			Handler:    _Daemon_EntryDuplicate_Handler,
		},
		{
			MethodName: "EntryGetConfig",
			Handler:    _Daemon_EntryGetConfig_Handler,
		},
		{
			MethodName: "EntrySetConfig",
			Handler:    _Daemon_EntrySetConfig_Handler,
		},
		{
			MethodName: "EntrySetMux",
			Handler:    _Daemon_EntrySetMux_Handler,
		},
		{
			MethodName: "InboundAdd",
			Handler:    _Daemon_InboundAdd_Handler,
		},
		{
			MethodName: "InboundList",
			Handler:    _Daemon_InboundList_Handler,
		},
		{
			MethodName: "InboundRemove",
			Handler:    _Daemon_InboundRemove_Handler,
		},
		{
			MethodName: "InboundDuplicate",
			Handler:    _Daemon_InboundDuplicate_Handler,
		},
		{
			MethodName: "InboundGetConfig",
			Handler:    _Daemon_InboundGetConfig_Handler,
		},
		{
			MethodName: "InboundSetConfig",
			Handler:    _Daemon_InboundSetConfig_Handler,
		},
		{
			MethodName: "InboundUserAdd",
			Handler:    _Daemon_InboundUserAdd_Handler,
		},
		{
			MethodName: "InboundUserList",
			Handler:    _Daemon_InboundUserList_Handler,
		},
		{
			MethodName: "InboundUserRemove",
			Handler:    _Daemon_InboundUserRemove_Handler,
		},
		{
			MethodName: "InboundUserSetEnabled",
			Handler:    _Daemon_InboundUserSetEnabled_Handler,
		},
		{
			MethodName: "Winners",
			Handler:    _Daemon_Winners_Handler,
		},
		{
			MethodName: "Traffic",
			Handler:    _Daemon_Traffic_Handler,
		},
		{
			MethodName: "TrafficLive",
			Handler:    _Daemon_TrafficLive_Handler,
		},
		{
			MethodName: "TrafficRetention",
			Handler:    _Daemon_TrafficRetention_Handler,
		},
		{
			MethodName: "ExportConfig",
			Handler:    _Daemon_ExportConfig_Handler,
		},
		{
			MethodName: "ImportConfig",
			Handler:    _Daemon_ImportConfig_Handler,
		},
		{
			MethodName: "SubAdd",
			Handler:    _Daemon_SubAdd_Handler,
		},
		{
			MethodName: "SubList",
			Handler:    _Daemon_SubList_Handler,
		},
		{
			MethodName: "SubRemove",
			Handler:    _Daemon_SubRemove_Handler,
		},
		{
			MethodName: "SubSetEnabled",
			Handler:    _Daemon_SubSetEnabled_Handler,
		},
		{
			MethodName: "SubRefresh",
			Handler:    _Daemon_SubRefresh_Handler,
		},
		{
			MethodName: "SubNodes",
			Handler:    _Daemon_SubNodes_Handler,
		},
		{
			MethodName: "SubSetNodeDisabled",
			Handler:    _Daemon_SubSetNodeDisabled_Handler,
		},
		{
			MethodName: "SubRename",
			Handler:    _Daemon_SubRename_Handler,
		},
		{
			MethodName: "SubSetOptions",
			Handler:    _Daemon_SubSetOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emx.proto",
}
