// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: emx.proto

package emxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daemon_Ping_FullMethodName               = "/emx.v1.Daemon/Ping"
	Daemon_Status_FullMethodName             = "/emx.v1.Daemon/Status"
	Daemon_Shutdown_FullMethodName           = "/emx.v1.Daemon/Shutdown"
	Daemon_TemplateList_FullMethodName       = "/emx.v1.Daemon/TemplateList"
	Daemon_EntryAdd_FullMethodName           = "/emx.v1.Daemon/EntryAdd"
	Daemon_EntryList_FullMethodName          = "/emx.v1.Daemon/EntryList"
	Daemon_EntryRemove_FullMethodName        = "/emx.v1.Daemon/EntryRemove"
	Daemon_EntryRename_FullMethodName        = "/emx.v1.Daemon/EntryRename"
	Daemon_InboundAdd_FullMethodName         = "/emx.v1.Daemon/InboundAdd"
	Daemon_InboundList_FullMethodName        = "/emx.v1.Daemon/InboundList"
	Daemon_InboundRemove_FullMethodName      = "/emx.v1.Daemon/InboundRemove"
	Daemon_Winners_FullMethodName            = "/emx.v1.Daemon/Winners"
	Daemon_SubAdd_FullMethodName             = "/emx.v1.Daemon/SubAdd"
	Daemon_SubList_FullMethodName            = "/emx.v1.Daemon/SubList"
	Daemon_SubRemove_FullMethodName          = "/emx.v1.Daemon/SubRemove"
	Daemon_SubSetEnabled_FullMethodName      = "/emx.v1.Daemon/SubSetEnabled"
	Daemon_SubRefresh_FullMethodName         = "/emx.v1.Daemon/SubRefresh"
	Daemon_SubNodes_FullMethodName           = "/emx.v1.Daemon/SubNodes"
	Daemon_SubSetNodeDisabled_FullMethodName = "/emx.v1.Daemon/SubSetNodeDisabled"
	Daemon_SubRename_FullMethodName          = "/emx.v1.Daemon/SubRename"
)

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Daemon is the control surface the CLI/TUI drives over the unix socket.
type DaemonClient interface {
	// Lifecycle / health.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	// Templates.
	TemplateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateListReply, error)
	// Entries (outbounds; a non-empty dialer makes one a master).
	EntryAdd(ctx context.Context, in *EntryAddRequest, opts ...grpc.CallOption) (*EntryReply, error)
	EntryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntryListReply, error)
	EntryRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	EntryRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error)
	// Inbounds (server listeners routed to a target).
	InboundAdd(ctx context.Context, in *InboundAddRequest, opts ...grpc.CallOption) (*InboundReply, error)
	InboundList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InboundListReply, error)
	InboundRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	// Winner: the current fastest (balancer-selected) node per master.
	Winners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WinnersReply, error)
	// Subscriptions (node pools consumed by masters via xraysub:NAME).
	SubAdd(ctx context.Context, in *SubAddRequest, opts ...grpc.CallOption) (*SubReply, error)
	SubList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubListReply, error)
	SubRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	SubSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error)
	SubRefresh(ctx context.Context, in *SubRefreshRequest, opts ...grpc.CallOption) (*SubRefreshReply, error)
	SubNodes(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SubNodesReply, error)
	SubSetNodeDisabled(ctx context.Context, in *SubNodeDisabledRequest, opts ...grpc.CallOption) (*Empty, error)
	SubRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error)
}

type daemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonClient(cc grpc.ClientConnInterface) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, Daemon_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, Daemon_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, Daemon_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) TemplateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplateListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateListReply)
	err := c.cc.Invoke(ctx, Daemon_TemplateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryAdd(ctx context.Context, in *EntryAddRequest, opts ...grpc.CallOption) (*EntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryReply)
	err := c.cc.Invoke(ctx, Daemon_EntryAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntryListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryListReply)
	err := c.cc.Invoke(ctx, Daemon_EntryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_EntryRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) EntryRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_EntryRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundAdd(ctx context.Context, in *InboundAddRequest, opts ...grpc.CallOption) (*InboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundReply)
	err := c.cc.Invoke(ctx, Daemon_InboundAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InboundListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundListReply)
	err := c.cc.Invoke(ctx, Daemon_InboundList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InboundRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_InboundRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Winners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WinnersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WinnersReply)
	err := c.cc.Invoke(ctx, Daemon_Winners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubAdd(ctx context.Context, in *SubAddRequest, opts ...grpc.CallOption) (*SubReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubReply)
	err := c.cc.Invoke(ctx, Daemon_SubAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubListReply)
	err := c.cc.Invoke(ctx, Daemon_SubList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRemove(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubSetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubSetEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRefresh(ctx context.Context, in *SubRefreshRequest, opts ...grpc.CallOption) (*SubRefreshReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubRefreshReply)
	err := c.cc.Invoke(ctx, Daemon_SubRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubNodes(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SubNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubNodesReply)
	err := c.cc.Invoke(ctx, Daemon_SubNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubSetNodeDisabled(ctx context.Context, in *SubNodeDisabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubSetNodeDisabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SubRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Daemon_SubRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
// All implementations must embed UnimplementedDaemonServer
// for forward compatibility.
//
// Daemon is the control surface the CLI/TUI drives over the unix socket.
type DaemonServer interface {
	// Lifecycle / health.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	// Templates.
	TemplateList(context.Context, *Empty) (*TemplateListReply, error)
	// Entries (outbounds; a non-empty dialer makes one a master).
	EntryAdd(context.Context, *EntryAddRequest) (*EntryReply, error)
	EntryList(context.Context, *Empty) (*EntryListReply, error)
	EntryRemove(context.Context, *IdRequest) (*Empty, error)
	EntryRename(context.Context, *RenameRequest) (*Empty, error)
	// Inbounds (server listeners routed to a target).
	InboundAdd(context.Context, *InboundAddRequest) (*InboundReply, error)
	InboundList(context.Context, *Empty) (*InboundListReply, error)
	InboundRemove(context.Context, *IdRequest) (*Empty, error)
	// Winner: the current fastest (balancer-selected) node per master.
	Winners(context.Context, *Empty) (*WinnersReply, error)
	// Subscriptions (node pools consumed by masters via xraysub:NAME).
	SubAdd(context.Context, *SubAddRequest) (*SubReply, error)
	SubList(context.Context, *Empty) (*SubListReply, error)
	SubRemove(context.Context, *IdRequest) (*Empty, error)
	SubSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error)
	SubRefresh(context.Context, *SubRefreshRequest) (*SubRefreshReply, error)
	SubNodes(context.Context, *IdRequest) (*SubNodesReply, error)
	SubSetNodeDisabled(context.Context, *SubNodeDisabledRequest) (*Empty, error)
	SubRename(context.Context, *RenameRequest) (*Empty, error)
	mustEmbedUnimplementedDaemonServer()
}

// UnimplementedDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServer struct{}

func (UnimplementedDaemonServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServer) Status(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDaemonServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServer) TemplateList(context.Context, *Empty) (*TemplateListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TemplateList not implemented")
}
func (UnimplementedDaemonServer) EntryAdd(context.Context, *EntryAddRequest) (*EntryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntryAdd not implemented")
}
func (UnimplementedDaemonServer) EntryList(context.Context, *Empty) (*EntryListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntryList not implemented")
}
func (UnimplementedDaemonServer) EntryRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntryRemove not implemented")
}
func (UnimplementedDaemonServer) EntryRename(context.Context, *RenameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntryRename not implemented")
}
func (UnimplementedDaemonServer) InboundAdd(context.Context, *InboundAddRequest) (*InboundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InboundAdd not implemented")
}
func (UnimplementedDaemonServer) InboundList(context.Context, *Empty) (*InboundListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InboundList not implemented")
}
func (UnimplementedDaemonServer) InboundRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InboundRemove not implemented")
}
func (UnimplementedDaemonServer) Winners(context.Context, *Empty) (*WinnersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Winners not implemented")
}
func (UnimplementedDaemonServer) SubAdd(context.Context, *SubAddRequest) (*SubReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubAdd not implemented")
}
func (UnimplementedDaemonServer) SubList(context.Context, *Empty) (*SubListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubList not implemented")
}
func (UnimplementedDaemonServer) SubRemove(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubRemove not implemented")
}
func (UnimplementedDaemonServer) SubSetEnabled(context.Context, *SetEnabledRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubSetEnabled not implemented")
}
func (UnimplementedDaemonServer) SubRefresh(context.Context, *SubRefreshRequest) (*SubRefreshReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubRefresh not implemented")
}
func (UnimplementedDaemonServer) SubNodes(context.Context, *IdRequest) (*SubNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubNodes not implemented")
}
func (UnimplementedDaemonServer) SubSetNodeDisabled(context.Context, *SubNodeDisabledRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubSetNodeDisabled not implemented")
}
func (UnimplementedDaemonServer) SubRename(context.Context, *RenameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubRename not implemented")
}
func (UnimplementedDaemonServer) mustEmbedUnimplementedDaemonServer() {}
func (UnimplementedDaemonServer) testEmbeddedByValue()                {}

// UnsafeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServer will
// result in compilation errors.
type UnsafeDaemonServer interface {
	mustEmbedUnimplementedDaemonServer()
}

func RegisterDaemonServer(s grpc.ServiceRegistrar, srv DaemonServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daemon_ServiceDesc, srv)
}

func _Daemon_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_TemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).TemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_TemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).TemplateList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryAdd(ctx, req.(*EntryAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_EntryRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).EntryRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_EntryRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).EntryRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundAdd(ctx, req.(*InboundAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InboundRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InboundRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_InboundRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InboundRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Winners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Winners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Winners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Winners(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubAdd(ctx, req.(*SubAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRemove(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubSetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubSetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubSetEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubSetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRefresh(ctx, req.(*SubRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubNodes(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubSetNodeDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubNodeDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubSetNodeDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubSetNodeDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubSetNodeDisabled(ctx, req.(*SubNodeDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SubRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SubRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_SubRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SubRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Daemon_ServiceDesc is the grpc.ServiceDesc for Daemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emx.v1.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Daemon_Ping_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Daemon_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Daemon_Shutdown_Handler,
		},
		{
			MethodName: "TemplateList",
			Handler:    _Daemon_TemplateList_Handler,
		},
		{
			MethodName: "EntryAdd",
			Handler:    _Daemon_EntryAdd_Handler,
		},
		{
			MethodName: "EntryList",
			Handler:    _Daemon_EntryList_Handler,
		},
		{
			MethodName: "EntryRemove",
			Handler:    _Daemon_EntryRemove_Handler,
		},
		{
			MethodName: "EntryRename",
			Handler:    _Daemon_EntryRename_Handler,
		},
		{
			MethodName: "InboundAdd",
			Handler:    _Daemon_InboundAdd_Handler,
		},
		{
			MethodName: "InboundList",
			Handler:    _Daemon_InboundList_Handler,
		},
		{
			MethodName: "InboundRemove",
			Handler:    _Daemon_InboundRemove_Handler,
		},
		{
			MethodName: "Winners",
			Handler:    _Daemon_Winners_Handler,
		},
		{
			MethodName: "SubAdd",
			Handler:    _Daemon_SubAdd_Handler,
		},
		{
			MethodName: "SubList",
			Handler:    _Daemon_SubList_Handler,
		},
		{
			MethodName: "SubRemove",
			Handler:    _Daemon_SubRemove_Handler,
		},
		{
			MethodName: "SubSetEnabled",
			Handler:    _Daemon_SubSetEnabled_Handler,
		},
		{
			MethodName: "SubRefresh",
			Handler:    _Daemon_SubRefresh_Handler,
		},
		{
			MethodName: "SubNodes",
			Handler:    _Daemon_SubNodes_Handler,
		},
		{
			MethodName: "SubSetNodeDisabled",
			Handler:    _Daemon_SubSetNodeDisabled_Handler,
		},
		{
			MethodName: "SubRename",
			Handler:    _Daemon_SubRename_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emx.proto",
}
